### ISSUE TITLE
After plugin install error generated on backend and frontend.

### ISSUE THREAD

**Issue by pwpdev** [wbcomdesigns/bp-job-manager#3]
![image4](https://user-images.githubusercontent.com/25028934/28965915-1fee573e-7931-11e7-8da6-3d38d2929da7.png)
php version: 5.6.0
buddypress version 2.9.0, 2.8.2
![image5](https://user-images.githubusercontent.com/25028934/28966472-0396e300-7934-11e7-8605-ded907912dd2.png)

**Comment by pallavigdev** [comment]
this is fixed.
